logFilters:
  # react-virtualized thinks it will only work with react 16.x
  - level: discard
    text: "terra-ui@workspace:. provides react (pce525) with version 17.0.2, which doesn't satisfy what react-virtualized requests"
  - level: discard
    text: "terra-ui@workspace:. provides react-dom (p6a7e3) with version 17.0.2, which doesn't satisfy what react-virtualized requests"
  # don't need to warn that we're not running scripts for packages whose only script is attribution
  # we've disabled their scripts to stop them being unplugged by yarn
  - code: YN0005
    level: discard

nodeLinker: pnp

packageExtensions:
  eslint-config-react-app@*:
    peerDependenciesMeta:
      "@babel/plugin-syntax-flow":
        optional: true
      "@babel/plugin-transform-react-jsx":
        optional: true
  fork-ts-checker-webpack-plugin@*:
    peerDependenciesMeta:
      typescript:
        optional: true
      webpack:
        optional: true
  jest-environment-puppeteer@*:
    peerDependencies:
      puppeteer: "*"
  react-scripts@*:
    dependencies:
      autoprefixer: "*"
  react-simplemde-editor@*:
    dependencies:
      "@babel/runtime": "*"
  terra-ui@*:
    dependencies:
      eslint: "*"
      eslint-config-react-app: "*"
      html-webpack-plugin: "*"
      webpack: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - ./.hooks/plugin-warning-logger.js

yarnPath: .yarn/releases/yarn-3.2.3.cjs
