runtime: python27
api_version: 1
threadsafe: true
default_expiration: "2m"

handlers:
- url: /(.*\.(css|eot|gz|html|ico|jpg|jpeg|js|json|map|png|svg|otf|ttf|woff|woff2))
  static_files: build/\1
  upload: build/(.*)
  secure: always
- url: /.*
  static_files: build/index.html
  upload: build/index.html
  secure: always
