

export const mockSelectedEntities = {
  'HCC1143_15': {
    'attributes': {
      'participant': 'subject_HCC1143',
      'sample_type': 'Tumor',
      'ref_fasta': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta',
      'ref_dict': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.dict',
      'ref_intervals': 'gs://cancer-exome-pipeline-demo-data/panel_100_genes.interval_list',
      'ref_ann': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.ann',
      'dna': 'gs://fc-d1f53ee4-4abe-4de0-91b2-597a609deddc/inDNA',
      'ref_sa': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.sa',
      'fastq2': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad_2.fastq',
      'ref_amb': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.amb',
      'fastq1': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad_1.fastq',
      'library': 'library_name',
      'strip_unpaired': 'TRUE',
      'sample': 'HCC1143_15',
      'ref_bwt': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.bwt',
      'platform': 'illumina',
      'bai': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad.bai',
      'bam': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad.bam',
      'ref_pac': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.pac'
    },
    'entityType': 'sample',
    'name': 'HCC1143_15'
  },
  'HCC1143_16': {
    'attributes': {
      'participant': 'subject_HCC1143',
      'sample_type': 'Tumor',
      'ref_fasta': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta',
      'ref_dict': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.dict',
      'ref_intervals': 'gs://cancer-exome-pipeline-demo-data/panel_100_genes.interval_list',
      'ref_ann': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.ann',
      'dna': 'gs://fc-d1f53ee4-4abe-4de0-91b2-597a609deddc/inDNA',
      'ref_sa': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.sa',
      'fastq2': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad_2.fastq',
      'ref_amb': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.amb',
      'fastq1': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad_1.fastq',
      'library': 'library_name',
      'strip_unpaired': 'TRUE',
      'sample': 'HCC1143_16',
      'ref_bwt': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.bwt',
      'platform': 'illumina',
      'bai': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad.bai',
      'bam': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad.bam',
      'ref_pac': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.pac'
    },
    'entityType': 'sample',
    'name': 'HCC1143_16'
  },
  'HCC1143_17': {
    'attributes': {
      'participant': 'subject_HCC1143',
      'sample_type': 'Tumor',
      'ref_fasta': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta',
      'ref_dict': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.dict',
      'ref_intervals': 'gs://cancer-exome-pipeline-demo-data/panel_100_genes.interval_list',
      'ref_ann': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.ann',
      'dna': 'gs://fc-d1f53ee4-4abe-4de0-91b2-597a609deddc/inDNA',
      'ref_sa': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.sa',
      'fastq2': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad_2.fastq',
      'ref_amb': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.amb',
      'fastq1': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad_1.fastq',
      'library': 'library_name',
      'strip_unpaired': 'TRUE',
      'sample': 'HCC1143_17',
      'ref_bwt': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.bwt',
      'platform': 'illumina',
      'bai': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad.bai',
      'bam': 'gs://cancer-exome-pipeline-demo-data/HCC1143.8_100_gene_250bp_pad.bam',
      'ref_pac': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.pac'
    },
    'entityType': 'sample',
    'name': 'HCC1143_17'
  },
  'HCC1143_18': {
    'attributes': {
      'participant': 'subject_HCC1143',
      'sample_type': 'Tumor',
      'ref_fasta': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta',
      'ref_dict': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.dict',
      'ref_intervals': 'gs://cancer-exome-pipeline-demo-data/panel_100_genes.interval_list',
      'ref_ann': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.ann',
      'dna': 'gs://fc-d1f53ee4-4abe-4de0-91b2-597a609deddc/inDNA',
      'ref_sa': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.sa',
      'fastq2': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad_2.fastq',
      'ref_amb': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.amb',
      'fastq1': 'gs://cancer-exome-pipeline-demo-data/HCC1143.7_100_gene_250bp_pad_1.fastq',
      'library': 'library_name',
      'strip_unpaired': 'TRUE',
      'sample': 'HCC1143_18',
      'ref_bwt': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.bwt',
      'platform': 'illumina',
      'bai': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad.bai',
      'bam': 'gs://cancer-exome-pipeline-demo-data/HCC1143.6_100_gene_250bp_pad.bam',
      'ref_pac': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.pac'
    },
    'entityType': 'sample',
    'name': 'HCC1143_18'
  },
  'HCC1143_19': {
    'attributes': {
      'participant': 'subject_HCC1143',
      'sample_type': 'Tumor',
      'ref_fasta': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta',
      'ref_dict': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.dict',
      'ref_intervals': 'gs://cancer-exome-pipeline-demo-data/panel_100_genes.interval_list',
      'ref_ann': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.ann',
      'dna': 'gs://fc-d1f53ee4-4abe-4de0-91b2-597a609deddc/inDNA',
      'ref_sa': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.sa',
      'fastq2': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad_2.fastq',
      'ref_amb': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.amb',
      'fastq1': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad_1.fastq',
      'library': 'library_name',
      'strip_unpaired': 'TRUE',
      'sample': 'HCC1143_19',
      'ref_bwt': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.bwt',
      'platform': 'illumina',
      'bai': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad.bai',
      'bam': 'gs://cancer-exome-pipeline-demo-data/HCC1143.5_100_gene_250bp_pad.bam',
      'ref_pac': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.pac'
    },
    'entityType': 'sample',
    'name': 'HCC1143_19'
  },
  'HCC1143_2': {
    'attributes': {
      'participant': 'subject_HCC1143',
      'sample_type': 'Tumor',
      'ref_fasta': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta',
      'ref_dict': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.dict',
      'ref_intervals': 'gs://cancer-exome-pipeline-demo-data/panel_100_genes.interval_list',
      'ref_ann': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.ann',
      'dna': 'gs://fc-d1f53ee4-4abe-4de0-91b2-597a609deddc/inDNA',
      'ref_sa': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.sa',
      'fastq2': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad_2.fastq',
      'ref_amb': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.amb',
      'fastq1': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad_1.fastq',
      'library': 'library_name',
      'strip_unpaired': 'TRUE',
      'sample': 'HCC1143_2',
      'ref_bwt': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.bwt',
      'platform': 'illumina',
      'bai': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad.bai',
      'bam': 'gs://cancer-exome-pipeline-demo-data/HCC1143.4_100_gene_250bp_pad.bam',
      'ref_pac': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.pac'
    },
    'entityType': 'sample',
    'name': 'HCC1143_2'
  },
  'HCC1143_20': {
    'attributes': {
      'participant': 'subject_HCC1143',
      'sample_type': 'Tumor',
      'ref_fasta': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta',
      'ref_dict': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.dict',
      'ref_intervals': 'gs://cancer-exome-pipeline-demo-data/panel_100_genes.interval_list',
      'ref_ann': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.ann',
      'dna': 'gs://fc-d1f53ee4-4abe-4de0-91b2-597a609deddc/inDNA',
      'ref_sa': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.sa',
      'fastq2': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad_2.fastq',
      'ref_amb': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.amb',
      'fastq1': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad_1.fastq',
      'library': 'library_name',
      'strip_unpaired': 'TRUE',
      'sample': 'HCC1143_20',
      'ref_bwt': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.bwt',
      'platform': 'illumina',
      'bai': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad.bai',
      'bam': 'gs://cancer-exome-pipeline-demo-data/HCC1143.3_100_gene_250bp_pad.bam',
      'ref_pac': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.pac'
    },
    'entityType': 'sample',
    'name': 'HCC1143_20'
  },
  'HCC1143_21': {
    'attributes': {
      'participant': 'subject_HCC1143',
      'sample_type': 'Tumor',
      'ref_fasta': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta',
      'ref_dict': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.dict',
      'ref_intervals': 'gs://cancer-exome-pipeline-demo-data/panel_100_genes.interval_list',
      'ref_ann': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.ann',
      'dna': 'gs://fc-d1f53ee4-4abe-4de0-91b2-597a609deddc/inDNA',
      'ref_sa': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.sa',
      'fastq2': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad_2.fastq',
      'ref_amb': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.amb',
      'fastq1': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad_1.fastq',
      'library': 'library_name',
      'strip_unpaired': 'TRUE',
      'sample': 'HCC1143_21',
      'ref_bwt': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.bwt',
      'platform': 'illumina',
      'bai': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad.bai',
      'bam': 'gs://cancer-exome-pipeline-demo-data/HCC1143.2_100_gene_250bp_pad.bam',
      'ref_pac': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.pac'
    },
    'entityType': 'sample',
    'name': 'HCC1143_21'
  },
  'HCC1143_22': {
    'attributes': {
      'participant': 'subject_HCC1143',
      'sample_type': 'Tumor',
      'ref_fasta': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta',
      'ref_dict': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.dict',
      'ref_intervals': 'gs://cancer-exome-pipeline-demo-data/panel_100_genes.interval_list',
      'ref_ann': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.ann',
      'dna': 'gs://fc-d1f53ee4-4abe-4de0-91b2-597a609deddc/inDNA',
      'ref_sa': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.sa',
      'fastq2': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad_2.fastq',
      'ref_amb': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.amb',
      'fastq1': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad_1.fastq',
      'library': 'library_name',
      'strip_unpaired': 'TRUE',
      'sample': 'HCC1143_22',
      'ref_bwt': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.bwt',
      'platform': 'illumina',
      'bai': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad.bai',
      'bam': 'gs://cancer-exome-pipeline-demo-data/HCC1143.1_100_gene_250bp_pad.bam',
      'ref_pac': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.pac'
    },
    'entityType': 'sample',
    'name': 'HCC1143_22'
  },
  'HCC1143_23': {
    'attributes': {
      'participant': 'subject_HCC1143',
      'sample_type': 'Tumor',
      'ref_fasta': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta',
      'ref_dict': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.dict',
      'ref_intervals': 'gs://cancer-exome-pipeline-demo-data/panel_100_genes.interval_list',
      'ref_ann': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.ann',
      'dna': 'gs://fc-d1f53ee4-4abe-4de0-91b2-597a609deddc/inDNA',
      'ref_sa': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.sa',
      'fastq2': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad_2.fastq',
      'ref_amb': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.amb',
      'fastq1': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad_1.fastq',
      'library': 'library_name',
      'strip_unpaired': 'TRUE',
      'sample': 'HCC1143_23',
      'ref_bwt': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.bwt',
      'platform': 'illumina',
      'bai': 'gs://cancer-exome-pipeline-demo-data/HCC1143.100_gene_250bp_pad.bai',
      'bam': 'gs://cancer-exome-pipeline-demo-data/HCC1145.100_gene_250bp_pad.bam',
      'ref_pac': 'gs://cancer-exome-pipeline-demo-data/Homo_sapiens_assembly19.fasta.64.pac'
    },
    'entityType': 'sample',
    'name': 'HCC1143_23'
  }
}

