export const JUPYTERLAB_GCP_FEATURE_ID = 'jupyterlab-gcp';
export const ENABLE_JUPYTERLAB_ID = 'enableJupyterLabGCP';
export const ENABLE_AZURE_PFB_IMPORT = 'enableAzurePfbImport';
export const ENABLE_AZURE_TDR_IMPORT = 'enableAzureTdrImport';
export const COHORT_BUILDER_CARD = 'cohortBuilderCard';
export const SPEND_REPORTING = 'spendReporting';
export const AUTO_GENERATE_DATA_TABLES = 'autoGenerateDataTables';
export const PREVIEW_COST_CAPPING = 'previewCostCapping';
export const GCP_BATCH = 'gcpBatch';

// If the groups option is defined for a FeaturePreview, it must contain at least one group.
type GroupsList = readonly [string, ...string[]];

export type FeaturePreview = {
  /**
   * ID for the feature. This is used to check if the feature is enabled and to toggle it enabled/disabled.
   */
  readonly id: string;

  /**
   * Name of the feature. Shown on the feature previews page.
   */
  readonly title: string;

  /**
   * Description for the feature. Shown on the feature previews page.
   */
  readonly description: string;

  /**
   * Optional list of groups. If specified, the feature will only appear on the feature previews page
   * for users that are a member of at least one of the specified groups.
   * This only applies in production. In dev environments, all features are available to all users.
   */
  readonly groups?: GroupsList;

  /**
   * Optional URL for feature documentation. Shown on the feature previews page.
   */
  readonly documentationUrl?: string;

  /**
   * Optional URL for users to provide feedback on the feature. Shown on the feature previews page.
   */
  readonly feedbackUrl?: string;

  /**
   * Optional date string for the last updated date. Shown on the feature previews page.
   */
  readonly lastUpdated?: string;
};

const featurePreviewsConfig: readonly FeaturePreview[] = [
  {
    id: JUPYTERLAB_GCP_FEATURE_ID,
    title: 'JupyterLab on GCP',
    description: 'Enabling this feature will allow you to launch notebooks using JupyterLab in GCP workspaces.',
    groups: ['preview-jupyterlab-gcp'],
    feedbackUrl: `mailto:dsp-sue@broadinstitute.org?subject=${encodeURIComponent('Feedback on JupyterLab (GCP)')}`,
    lastUpdated: '12/22/2022',
  },
  {
    id: COHORT_BUILDER_CARD,
    title: 'Cohort Builder Card',
    description:
      'Enabling this feature will show the card for the demo cohort builder in the Datasets tab in the Library.',
    groups: ['CohortBuilderUsers'],
    feedbackUrl: `mailto:dsp-data-exploration@broadinstitute.org?subject=${encodeURIComponent(
      'Feedback on Cohort Builder Card'
    )}`,
    lastUpdated: '7/25/2024',
  },
  {
    id: SPEND_REPORTING,
    title: 'Improved Spend Reports',
    description:
      'Enabling this feature will show billing project owners costs associated with all workspaces in billing projects with spend reporting enabled. Additional updates to spend reports coming soon!',
    feedbackUrl: 'https://support.terra.bio/hc/en-us/articles/31182586327323',
    lastUpdated: '01/17/2025',
  },
  {
    id: AUTO_GENERATE_DATA_TABLES,
    title: 'Autogenerate data table for single and paired end sequencing',
    description:
      'Enabling this feature will show a new option in the data uploader to autogenerate a data table instead of uploading your own TSV. This feature will attempt to automatch known file patterns for single and paired end sequencing and autogenerate a data table linking to those files.',
    feedbackUrl: 'https://support.terra.bio/hc/en-us/articles/31258673632923',
    lastUpdated: '11/26/2024',
  },
  {
    id: PREVIEW_COST_CAPPING,
    title: 'Workflow Cost Thresholds',
    description:
      'Enabling this feature will show a new workflow configuration option to add a user-configurable cost threshold to the workflow. Workflows will be terminated once they exceed the configured value.',
    feedbackUrl: 'https://support.terra.bio/hc/en-us/articles/31269696049307',
    lastUpdated: '2/28/2025',
  },
  {
    id: GCP_BATCH,
    title: 'Run workflows on GCP Batch',
    description:
      'Enabling this feature allows workflows to be processed by the GCP Batch service, rather than the former Cloud Life Sciences API. All Terra workflows will be transitioned to GCP Batch by mid-2025.',
    groups: ['preview-batch'],
    feedbackUrl: `mailto:dsp-analysis@broadinstitute.org?subject=${encodeURIComponent('Feedback on GCP Batch')}`,
    lastUpdated: '12/12/2024',
  },
];

export default featurePreviewsConfig;
