#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

FORBIDDEN='private_key|sa_key_var|SA_KEY_JSON'

if git diff --cached -U0 | grep -E --color ${FORBIDDEN}; then
  echo
  echo 'COMMIT REJECTED: Found changes containing sensitive keywords.'
  echo 'Misuse of these keywords can potentially cause security vulnerabilities, even if they are pushed to a branch.'
  echo 'Please remove these changes, or else check with another member of the team before proceeding.'
  echo
  exit 1
fi

yarn lint-staged
