export const chooseRows = Symbol('choose rows')
export const chooseSetComponents = Symbol('choose set components')
export const chooseSets = Symbol('choose sets')
export const processAll = Symbol('process all')
export const processAllAsSet = Symbol('process all set components')
export const processMergedSet = Symbol('process merged set')
export const processSnapshotTable = Symbol('process snapshot table')
